// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace ediri.Akp
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("akp");

        private static readonly __Value<string?> _apiKeyId = new __Value<string?>(() => __config.Get("apiKeyId") ?? Utilities.GetEnv("AKUITY_API_KEY_ID"));
        /// <summary>
        /// API Key Id. Use environment variable `AKUITY_API_KEY_ID`
        /// </summary>
        public static string? ApiKeyId
        {
            get => _apiKeyId.Get();
            set => _apiKeyId.Set(value);
        }

        private static readonly __Value<string?> _apiKeySecret = new __Value<string?>(() => __config.Get("apiKeySecret") ?? Utilities.GetEnv("AKUITY_API_KEY_SECRET"));
        /// <summary>
        /// API Key Secret, Use environment variable `AKUITY_API_KEY_SECRET`
        /// </summary>
        public static string? ApiKeySecret
        {
            get => _apiKeySecret.Get();
            set => _apiKeySecret.Set(value);
        }

        private static readonly __Value<string?> _orgName = new __Value<string?>(() => __config.Get("orgName"));
        /// <summary>
        /// Organization Name
        /// </summary>
        public static string? OrgName
        {
            get => _orgName.Get();
            set => _orgName.Set(value);
        }

        private static readonly __Value<string?> _serverUrl = new __Value<string?>(() => __config.Get("serverUrl") ?? Utilities.GetEnv("AKUITY_SERVER_URL"));
        /// <summary>
        /// Akuity Platform API URL, default: `https://akuity.cloud`. You can use environment variable `AKUITY_SERVER_URL` instead
        /// </summary>
        public static string? ServerUrl
        {
            get => _serverUrl.Get();
            set => _serverUrl.Set(value);
        }

        private static readonly __Value<bool?> _skipTlsVerify = new __Value<bool?>(() => __config.GetBoolean("skipTlsVerify"));
        /// <summary>
        /// Skip TLS Verify. Only use for testing self-hosted version
        /// </summary>
        public static bool? SkipTlsVerify
        {
            get => _skipTlsVerify.Get();
            set => _skipTlsVerify.Set(value);
        }

    }
}
