# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiKeyId: Optional[str]
"""
API Key Id. Use environment variable `AKUITY_API_KEY_ID`
"""

apiKeySecret: Optional[str]
"""
API Key Secret, Use environment variable `AKUITY_API_KEY_SECRET`
"""

orgName: Optional[str]
"""
Organization Name
"""

serverUrl: Optional[str]
"""
Akuity Platform API URL, default: `https://akuity.cloud`. You can use environment variable `AKUITY_SERVER_URL` instead
"""

skipTlsVerify: Optional[bool]
"""
Skip TLS Verify. Only use for testing self-hosted version
"""

