// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("akp");

/**
 * API Key Id. Use environment variable `AKUITY_API_KEY_ID`
 */
export declare const apiKeyId: string | undefined;
Object.defineProperty(exports, "apiKeyId", {
    get() {
        return __config.get("apiKeyId") ?? utilities.getEnv("AKUITY_API_KEY_ID");
    },
    enumerable: true,
});

/**
 * API Key Secret, Use environment variable `AKUITY_API_KEY_SECRET`
 */
export declare const apiKeySecret: string | undefined;
Object.defineProperty(exports, "apiKeySecret", {
    get() {
        return __config.get("apiKeySecret") ?? utilities.getEnv("AKUITY_API_KEY_SECRET");
    },
    enumerable: true,
});

/**
 * Organization Name
 */
export declare const orgName: string | undefined;
Object.defineProperty(exports, "orgName", {
    get() {
        return __config.get("orgName");
    },
    enumerable: true,
});

/**
 * Akuity Platform API URL, default: `https://akuity.cloud`. You can use environment variable `AKUITY_SERVER_URL` instead
 */
export declare const serverUrl: string | undefined;
Object.defineProperty(exports, "serverUrl", {
    get() {
        return __config.get("serverUrl") ?? utilities.getEnv("AKUITY_SERVER_URL");
    },
    enumerable: true,
});

/**
 * Skip TLS Verify. Only use for testing self-hosted version
 */
export declare const skipTlsVerify: boolean | undefined;
Object.defineProperty(exports, "skipTlsVerify", {
    get() {
        return __config.getObject<boolean>("skipTlsVerify");
    },
    enumerable: true,
});

