// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class ClusterSpec
    {
        /// <summary>
        /// Cluster data
        /// </summary>
        public readonly Outputs.ClusterSpecData Data;
        /// <summary>
        /// Cluster description
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// If the agent is namespace scoped
        /// </summary>
        public readonly bool? NamespaceScoped;

        [OutputConstructor]
        private ClusterSpec(
            Outputs.ClusterSpecData data,

            string? description,

            bool? namespaceScoped)
        {
            Data = data;
            Description = description;
            NamespaceScoped = namespaceScoped;
        }
    }
}
