// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetClusterSpecDataManagedClusterConfigResult
    {
        /// <summary>
        /// The key in the secret for the managed cluster config
        /// </summary>
        public readonly string SecretKey;
        /// <summary>
        /// The name of the secret for the managed cluster config
        /// </summary>
        public readonly string SecretName;

        [OutputConstructor]
        private GetClusterSpecDataManagedClusterConfigResult(
            string secretKey,

            string secretName)
        {
            SecretKey = secretKey;
            SecretName = secretName;
        }
    }
}
