// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetInstanceArgocdSpecInstanceSpecAgentPermissionsRuleResult
    {
        /// <summary>
        /// API groups of the rule.
        /// </summary>
        public readonly ImmutableArray<string> ApiGroups;
        /// <summary>
        /// Resources of the rule.
        /// </summary>
        public readonly ImmutableArray<string> Resources;
        /// <summary>
        /// Verbs of the rule.
        /// </summary>
        public readonly ImmutableArray<string> Verbs;

        [OutputConstructor]
        private GetInstanceArgocdSpecInstanceSpecAgentPermissionsRuleResult(
            ImmutableArray<string> apiGroups,

            ImmutableArray<string> resources,

            ImmutableArray<string> verbs)
        {
            ApiGroups = apiGroups;
            Resources = resources;
            Verbs = verbs;
        }
    }
}
