// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetInstanceConfigManagementPluginsSpecDiscoverFindResult
    {
        /// <summary>
        /// Arguments for the find command
        /// </summary>
        public readonly ImmutableArray<string> Args;
        /// <summary>
        /// The find command runs in the repository's root directory. To match, it must exit with status code 0 and produce non-empty output to standard out.
        /// </summary>
        public readonly ImmutableArray<string> Commands;
        /// <summary>
        /// This does the same thing as `file_name`, but it supports double-start (nested directory) glob patterns.
        /// </summary>
        public readonly string Glob;

        [OutputConstructor]
        private GetInstanceConfigManagementPluginsSpecDiscoverFindResult(
            ImmutableArray<string> args,

            ImmutableArray<string> commands,

            string glob)
        {
            Args = args;
            Commands = commands;
            Glob = glob;
        }
    }
}
