// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetInstanceArgocdSpecInstanceSpecAppSetDelegateResult
    {
        /// <summary>
        /// Use managed cluster
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecAppSetDelegateManagedClusterResult ManagedCluster;

        [OutputConstructor]
        private GetInstanceArgocdSpecInstanceSpecAppSetDelegateResult(Outputs.GetInstanceArgocdSpecInstanceSpecAppSetDelegateManagedClusterResult managedCluster)
        {
            ManagedCluster = managedCluster;
        }
    }
}
