// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetInstanceConfigManagementPluginsSpecParametersStaticResult
    {
        /// <summary>
        /// This field communicates the parameter's default value to the UI if the parameter is an `array`.
        /// </summary>
        public readonly ImmutableArray<string> Arrays;
        /// <summary>
        /// Collection Type describes what type of value this parameter accepts (string, array, or map) and allows the UI to present a form to match that type. Default is `string`. This field must be present for non-string types. It will not be inferred from the presence of an `array` or `map` field.
        /// </summary>
        public readonly string CollectionType;
        /// <summary>
        /// Item type tells the UI how to present the parameter's value (or, for arrays and maps, values). Default is `string`. Examples of other types which may be supported in the future are `boolean` or `number`. Even if the itemType is not `string`, the parameter value from the Application spec will be sent to the plugin as a string. It's up to the plugin to do the appropriate conversion.
        /// </summary>
        public readonly string ItemType;
        /// <summary>
        /// This field communicates the parameter's default value to the UI if the parameter is a `map`.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Map;
        /// <summary>
        /// Parameter name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Whether the Parameter is required or not. If this field is set to true, the UI will indicate to the user that they must set the value. Default to false.
        /// </summary>
        public readonly bool Required;
        /// <summary>
        /// This field communicates the parameter's default value to the UI if the parameter is a `string`.
        /// </summary>
        public readonly string String;
        /// <summary>
        /// Title and description of the parameter
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// Tooltip of the Parameter, will be shown when hovering over the title
        /// </summary>
        public readonly string Tooltip;

        [OutputConstructor]
        private GetInstanceConfigManagementPluginsSpecParametersStaticResult(
            ImmutableArray<string> arrays,

            string collectionType,

            string itemType,

            ImmutableDictionary<string, string> map,

            string name,

            bool required,

            string @string,

            string title,

            string tooltip)
        {
            Arrays = arrays;
            CollectionType = collectionType;
            ItemType = itemType;
            Map = map;
            Name = name;
            Required = required;
            String = @string;
            Title = title;
            Tooltip = tooltip;
        }
    }
}
