// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetInstanceArgocdSpecInstanceSpecResult
    {
        /// <summary>
        /// Select cluster in which you want to Install Application Set controller
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecAppSetDelegateResult AppSetDelegate;
        /// <summary>
        /// Configures Application Set policy settings.
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecAppsetPolicyResult AppsetPolicy;
        /// <summary>
        /// Enable Powerful AI-powered assistant Extension. It helps analyze Kubernetes resources behavior and provides suggestions about resolving issues.
        /// </summary>
        public readonly bool AssistantExtensionEnabled;
        /// <summary>
        /// Enable Audit Extension. Set this to `true` to install Audit Extension to Argo CD instance.
        /// </summary>
        public readonly bool AuditExtensionEnabled;
        /// <summary>
        /// Enable ip allow list for cluster agents
        /// </summary>
        public readonly bool BackendIpAllowListEnabled;
        /// <summary>
        /// Default values for cluster agents
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecClusterCustomizationDefaultsResult ClusterCustomizationDefaults;
        /// <summary>
        /// Enable Declarative Management
        /// </summary>
        public readonly bool DeclarativeManagementEnabled;
        /// <summary>
        /// Extensions
        /// </summary>
        public readonly ImmutableArray<Outputs.GetInstanceArgocdSpecInstanceSpecExtensionResult> Extensions;
        /// <summary>
        /// Host Aliases that override the DNS entries for control plane Argo CD components such as API Server and Dex.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetInstanceArgocdSpecInstanceSpecHostAliasResult> HostAliases;
        /// <summary>
        /// Select cluster in which you want to Install Image Updater
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecImageUpdaterDelegateResult ImageUpdaterDelegate;
        /// <summary>
        /// Enable Image Updater
        /// </summary>
        public readonly bool ImageUpdaterEnabled;
        /// <summary>
        /// IP allow list
        /// </summary>
        public readonly ImmutableArray<Outputs.GetInstanceArgocdSpecInstanceSpecIpAllowListResult> IpAllowLists;
        /// <summary>
        /// In case some clusters don't have network access to your private Git provider you can delegate these operations to one specific cluster.
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecRepoServerDelegateResult RepoServerDelegate;
        /// <summary>
        /// Instance subdomain. By default equals to instance id
        /// </summary>
        public readonly string Subdomain;
        /// <summary>
        /// Enable Sync History Extension. Sync count and duration graphs as well as event details table on Argo CD application details page.
        /// </summary>
        public readonly bool SyncHistoryExtensionEnabled;

        [OutputConstructor]
        private GetInstanceArgocdSpecInstanceSpecResult(
            Outputs.GetInstanceArgocdSpecInstanceSpecAppSetDelegateResult appSetDelegate,

            Outputs.GetInstanceArgocdSpecInstanceSpecAppsetPolicyResult appsetPolicy,

            bool assistantExtensionEnabled,

            bool auditExtensionEnabled,

            bool backendIpAllowListEnabled,

            Outputs.GetInstanceArgocdSpecInstanceSpecClusterCustomizationDefaultsResult clusterCustomizationDefaults,

            bool declarativeManagementEnabled,

            ImmutableArray<Outputs.GetInstanceArgocdSpecInstanceSpecExtensionResult> extensions,

            ImmutableArray<Outputs.GetInstanceArgocdSpecInstanceSpecHostAliasResult> hostAliases,

            Outputs.GetInstanceArgocdSpecInstanceSpecImageUpdaterDelegateResult imageUpdaterDelegate,

            bool imageUpdaterEnabled,

            ImmutableArray<Outputs.GetInstanceArgocdSpecInstanceSpecIpAllowListResult> ipAllowLists,

            Outputs.GetInstanceArgocdSpecInstanceSpecRepoServerDelegateResult repoServerDelegate,

            string subdomain,

            bool syncHistoryExtensionEnabled)
        {
            AppSetDelegate = appSetDelegate;
            AppsetPolicy = appsetPolicy;
            AssistantExtensionEnabled = assistantExtensionEnabled;
            AuditExtensionEnabled = auditExtensionEnabled;
            BackendIpAllowListEnabled = backendIpAllowListEnabled;
            ClusterCustomizationDefaults = clusterCustomizationDefaults;
            DeclarativeManagementEnabled = declarativeManagementEnabled;
            Extensions = extensions;
            HostAliases = hostAliases;
            ImageUpdaterDelegate = imageUpdaterDelegate;
            ImageUpdaterEnabled = imageUpdaterEnabled;
            IpAllowLists = ipAllowLists;
            RepoServerDelegate = repoServerDelegate;
            Subdomain = subdomain;
            SyncHistoryExtensionEnabled = syncHistoryExtensionEnabled;
        }
    }
}
