// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class GetInstanceArgocdSpecInstanceSpecImageUpdaterDelegateResult
    {
        /// <summary>
        /// If use control plane or not
        /// </summary>
        public readonly bool ControlPlane;
        /// <summary>
        /// If use managed cluster or not
        /// </summary>
        public readonly Outputs.GetInstanceArgocdSpecInstanceSpecImageUpdaterDelegateManagedClusterResult ManagedCluster;

        [OutputConstructor]
        private GetInstanceArgocdSpecInstanceSpecImageUpdaterDelegateResult(
            bool controlPlane,

            Outputs.GetInstanceArgocdSpecInstanceSpecImageUpdaterDelegateManagedClusterResult managedCluster)
        {
            ControlPlane = controlPlane;
            ManagedCluster = managedCluster;
        }
    }
}
