// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class InstanceConfigManagementPlugins
    {
        /// <summary>
        /// Whether this plugin is enabled or not. Default to false.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Image to use for the plugin
        /// </summary>
        public readonly string Image;
        /// <summary>
        /// Plugin spec
        /// </summary>
        public readonly Outputs.InstanceConfigManagementPluginsSpec Spec;

        [OutputConstructor]
        private InstanceConfigManagementPlugins(
            bool? enabled,

            string image,

            Outputs.InstanceConfigManagementPluginsSpec spec)
        {
            Enabled = enabled;
            Image = image;
            Spec = spec;
        }
    }
}
