// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Outputs
{

    [OutputType]
    public sealed class InstanceArgocdSpecInstanceSpecExtension
    {
        /// <summary>
        /// Extension ID
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Extension version
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private InstanceArgocdSpecInstanceSpecExtension(
            string id,

            string version)
        {
            Id = id;
            Version = version;
        }
    }
}
