// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/dirien/pulumi-akp/sdk/go/akp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// API Key Id. Use environment variable `AKUITY_API_KEY_ID`
func GetApiKeyId(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "akp:apiKeyId")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "AKUITY_API_KEY_ID"); d != nil {
		value = d.(string)
	}
	return value
}

// API Key Secret, Use environment variable `AKUITY_API_KEY_SECRET`
func GetApiKeySecret(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "akp:apiKeySecret")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "AKUITY_API_KEY_SECRET"); d != nil {
		value = d.(string)
	}
	return value
}

// Organization Name
func GetOrgName(ctx *pulumi.Context) string {
	return config.Get(ctx, "akp:orgName")
}

// Akuity Platform API URL, default: `https://akuity.cloud`. You can use environment variable `AKUITY_SERVER_URL` instead
func GetServerUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "akp:serverUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "AKUITY_SERVER_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// Skip TLS Verify. Only use for testing self-hosted version
func GetSkipTlsVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "akp:skipTlsVerify")
}
