// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class ClusterKubeConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// PEM-encoded client certificate for TLS authentication.
        /// </summary>
        [Input("clientCertificate")]
        public Input<string>? ClientCertificate { get; set; }

        [Input("clientKey")]
        private Input<string>? _clientKey;

        /// <summary>
        /// PEM-encoded client certificate key for TLS authentication.
        /// </summary>
        public Input<string>? ClientKey
        {
            get => _clientKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// PEM-encoded root certificates bundle for TLS authentication.
        /// </summary>
        [Input("clusterCaCertificate")]
        public Input<string>? ClusterCaCertificate { get; set; }

        /// <summary>
        /// Context name to load from the kube config file.
        /// </summary>
        [Input("configContext")]
        public Input<string>? ConfigContext { get; set; }

        [Input("configContextAuthInfo")]
        public Input<string>? ConfigContextAuthInfo { get; set; }

        [Input("configContextCluster")]
        public Input<string>? ConfigContextCluster { get; set; }

        /// <summary>
        /// Path to the kube config file.
        /// </summary>
        [Input("configPath")]
        public Input<string>? ConfigPath { get; set; }

        [Input("configPaths")]
        private InputList<string>? _configPaths;

        /// <summary>
        /// A list of paths to kube config files.
        /// </summary>
        public InputList<string> ConfigPaths
        {
            get => _configPaths ?? (_configPaths = new InputList<string>());
            set => _configPaths = value;
        }

        /// <summary>
        /// The hostname (in form of URI) of Kubernetes master.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// Whether server should be accessed without verifying the TLS certificate.
        /// </summary>
        [Input("insecure")]
        public Input<bool>? Insecure { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password to use for HTTP basic authentication when accessing the Kubernetes master endpoint.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// URL to the proxy to be used for all API requests
        /// </summary>
        [Input("proxyUrl")]
        public Input<string>? ProxyUrl { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Token to authenticate an service account
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The username to use for HTTP basic authentication when accessing the Kubernetes master endpoint.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public ClusterKubeConfigArgs()
        {
        }
        public static new ClusterKubeConfigArgs Empty => new ClusterKubeConfigArgs();
    }
}
