// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class ClusterSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster data
        /// </summary>
        [Input("data", required: true)]
        public Input<Inputs.ClusterSpecDataArgs> Data { get; set; } = null!;

        /// <summary>
        /// Cluster description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// If the agent is namespace scoped
        /// </summary>
        [Input("namespaceScoped")]
        public Input<bool>? NamespaceScoped { get; set; }

        public ClusterSpecArgs()
        {
        }
        public static new ClusterSpecArgs Empty => new ClusterSpecArgs();
    }
}
