// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceArgocdSpecInstanceSpecRepoServerDelegateManagedClusterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster name
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        public InstanceArgocdSpecInstanceSpecRepoServerDelegateManagedClusterArgs()
        {
        }
        public static new InstanceArgocdSpecInstanceSpecRepoServerDelegateManagedClusterArgs Empty => new InstanceArgocdSpecInstanceSpecRepoServerDelegateManagedClusterArgs();
    }
}
