// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceConfigManagementPluginsSpecParametersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Dynamic parameter announcements are announcements specific to an Application handled by this plugin. For example, the values for a Helm chart's values.yaml file could be sent as parameter announcements.
        /// </summary>
        [Input("dynamic")]
        public Input<Inputs.InstanceConfigManagementPluginsSpecParametersDynamicArgs>? Dynamic { get; set; }

        [Input("statics")]
        private InputList<Inputs.InstanceConfigManagementPluginsSpecParametersStaticArgs>? _statics;

        /// <summary>
        /// Static parameter announcements are sent to the UI for all Applications handled by this plugin. Think of the `string`, `array`, and `map` values set here as defaults. It is up to the plugin author to make sure that these default values actually reflect the plugin's behavior if the user doesn't explicitly set different values for those parameters.
        /// </summary>
        public InputList<Inputs.InstanceConfigManagementPluginsSpecParametersStaticArgs> Statics
        {
            get => _statics ?? (_statics = new InputList<Inputs.InstanceConfigManagementPluginsSpecParametersStaticArgs>());
            set => _statics = value;
        }

        public InstanceConfigManagementPluginsSpecParametersArgs()
        {
        }
        public static new InstanceConfigManagementPluginsSpecParametersArgs Empty => new InstanceConfigManagementPluginsSpecParametersArgs();
    }
}
