// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceArgocdSpecInstanceSpecCrossplaneExtensionArgs : global::Pulumi.ResourceArgs
    {
        [Input("resources")]
        private InputList<Inputs.InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs>? _resources;

        /// <summary>
        /// Glob patterns of the resources to match.
        /// </summary>
        public InputList<Inputs.InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs> Resources
        {
            get => _resources ?? (_resources = new InputList<Inputs.InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs>());
            set => _resources = value;
        }

        public InstanceArgocdSpecInstanceSpecCrossplaneExtensionArgs()
        {
        }
        public static new InstanceArgocdSpecInstanceSpecCrossplaneExtensionArgs Empty => new InstanceArgocdSpecInstanceSpecCrossplaneExtensionArgs();
    }
}
