// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceArgocdSpecInstanceSpecAppsetPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows per `ApplicationSet` sync policy.
        /// </summary>
        [Input("overridePolicy")]
        public Input<bool>? OverridePolicy { get; set; }

        /// <summary>
        /// Policy restricts what types of modifications will be made to managed Argo CD `Application` resources.
        /// Available options: `sync`, `create-only`, `create-delete`, and `create-update`.
        ///   - Policy `sync`(default): Update and delete are allowed.
        ///   - Policy `create-only`: Prevents ApplicationSet controller from modifying or deleting Applications.
        ///   - Policy `create-update`: Prevents ApplicationSet controller from deleting Applications. Update is allowed.
        ///   - Policy `create-delete`: Prevents ApplicationSet controller from modifying Applications, Delete is allowed.
        /// </summary>
        [Input("policy")]
        public Input<string>? Policy { get; set; }

        public InstanceArgocdSpecInstanceSpecAppsetPolicyArgs()
        {
        }
        public static new InstanceArgocdSpecInstanceSpecAppsetPolicyArgs Empty => new InstanceArgocdSpecInstanceSpecAppsetPolicyArgs();
    }
}
