// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Glob pattern of the group to match.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        public InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs()
        {
        }
        public static new InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs Empty => new InstanceArgocdSpecInstanceSpecCrossplaneExtensionResourceArgs();
    }
}
