// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceArgocdSpecInstanceSpecAppSetDelegateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Use managed cluster
        /// </summary>
        [Input("managedCluster")]
        public Input<Inputs.InstanceArgocdSpecInstanceSpecAppSetDelegateManagedClusterArgs>? ManagedCluster { get; set; }

        public InstanceArgocdSpecInstanceSpecAppSetDelegateArgs()
        {
        }
        public static new InstanceArgocdSpecInstanceSpecAppSetDelegateArgs Empty => new InstanceArgocdSpecInstanceSpecAppSetDelegateArgs();
    }
}
