// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceConfigManagementPluginsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether this plugin is enabled or not. Default to false.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Image to use for the plugin
        /// </summary>
        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        /// <summary>
        /// Plugin spec
        /// </summary>
        [Input("spec", required: true)]
        public Input<Inputs.InstanceConfigManagementPluginsSpecGetArgs> Spec { get; set; } = null!;

        public InstanceConfigManagementPluginsGetArgs()
        {
        }
        public static new InstanceConfigManagementPluginsGetArgs Empty => new InstanceConfigManagementPluginsGetArgs();
    }
}
