// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceConfigManagementPluginsSpecDiscoverGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A glob pattern (https://pkg.go.dev/path/filepath#Glob) that is applied to the Application's source directory. If there is a match, this plugin may be used for the Application.
        /// </summary>
        [Input("fileName")]
        public Input<string>? FileName { get; set; }

        /// <summary>
        /// Find config
        /// </summary>
        [Input("find")]
        public Input<Inputs.InstanceConfigManagementPluginsSpecDiscoverFindGetArgs>? Find { get; set; }

        public InstanceConfigManagementPluginsSpecDiscoverGetArgs()
        {
        }
        public static new InstanceConfigManagementPluginsSpecDiscoverGetArgs Empty => new InstanceConfigManagementPluginsSpecDiscoverGetArgs();
    }
}
