// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Akp.Inputs
{

    public sealed class InstanceArgocdSpecInstanceSpecExtensionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Extension ID
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Extension version
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public InstanceArgocdSpecInstanceSpecExtensionGetArgs()
        {
        }
        public static new InstanceArgocdSpecInstanceSpecExtensionGetArgs Empty => new InstanceArgocdSpecInstanceSpecExtensionGetArgs();
    }
}
