// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Gets information about a cluster by its name and Argo CD instance ID
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as akp from "@pulumi/akp";
 *
 * const exampleInstance = akp.getInstance({
 *     name: "test",
 * });
 * const exampleCluster = exampleInstance.then(exampleInstance => akp.getCluster({
 *     instanceId: exampleInstance.id,
 *     name: "test",
 * }));
 * ```
 */
export function getCluster(args: GetClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("akp:index/getCluster:getCluster", {
        "instanceId": args.instanceId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCluster.
 */
export interface GetClusterArgs {
    /**
     * Argo CD instance ID
     */
    instanceId: string;
    /**
     * Cluster name
     */
    name: string;
}

/**
 * A collection of values returned by getCluster.
 */
export interface GetClusterResult {
    /**
     * Annotations
     */
    readonly annotations: {[key: string]: string};
    /**
     * Cluster ID
     */
    readonly id: string;
    /**
     * Argo CD instance ID
     */
    readonly instanceId: string;
    readonly kubeConfig: outputs.GetClusterKubeConfig;
    /**
     * Labels
     */
    readonly labels: {[key: string]: string};
    /**
     * Cluster name
     */
    readonly name: string;
    /**
     * Agent installation namespace
     */
    readonly namespace: string;
    /**
     * Remove agent Kubernetes resources from the managed cluster when destroying cluster
     */
    readonly removeAgentResourcesOnDestroy: boolean;
    /**
     * Cluster spec
     */
    readonly spec: outputs.GetClusterSpec;
}
/**
 * Gets information about a cluster by its name and Argo CD instance ID
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as akp from "@pulumi/akp";
 *
 * const exampleInstance = akp.getInstance({
 *     name: "test",
 * });
 * const exampleCluster = exampleInstance.then(exampleInstance => akp.getCluster({
 *     instanceId: exampleInstance.id,
 *     name: "test",
 * }));
 * ```
 */
export function getClusterOutput(args: GetClusterOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetClusterResult> {
    return pulumi.output(args).apply((a: any) => getCluster(a, opts))
}

/**
 * A collection of arguments for invoking getCluster.
 */
export interface GetClusterOutputArgs {
    /**
     * Argo CD instance ID
     */
    instanceId: pulumi.Input<string>;
    /**
     * Cluster name
     */
    name: pulumi.Input<string>;
}
