// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Gets information about an Argo CD instance by its name
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as akp from "@pulumi/akp";
 *
 * const example = akp.getInstance({
 *     name: "test",
 * });
 * ```
 */
export function getInstance(args: GetInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetInstanceResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("akp:index/getInstance:getInstance", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstance.
 */
export interface GetInstanceArgs {
    name: string;
}

/**
 * A collection of values returned by getInstance.
 */
export interface GetInstanceResult {
    readonly applicationSetSecret: {[key: string]: string};
    readonly argocd: outputs.GetInstanceArgocd;
    readonly argocdCm: {[key: string]: string};
    readonly argocdImageUpdaterConfig: {[key: string]: string};
    readonly argocdImageUpdaterSecret: {[key: string]: string};
    readonly argocdImageUpdaterSshConfig: {[key: string]: string};
    readonly argocdNotificationsCm: {[key: string]: string};
    readonly argocdNotificationsSecret: {[key: string]: string};
    readonly argocdRbacCm: {[key: string]: string};
    readonly argocdSecret: {[key: string]: string};
    readonly argocdSshKnownHostsCm: {[key: string]: string};
    readonly argocdTlsCertsCm: {[key: string]: string};
    readonly configManagementPlugins: {[key: string]: outputs.GetInstanceConfigManagementPlugins};
    readonly id: string;
    readonly name: string;
    readonly repoCredentialSecrets: {[key: string]: {[key: string]: string}};
    readonly repoTemplateCredentialSecrets: {[key: string]: {[key: string]: string}};
}
/**
 * Gets information about an Argo CD instance by its name
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as akp from "@pulumi/akp";
 *
 * const example = akp.getInstance({
 *     name: "test",
 * });
 * ```
 */
export function getInstanceOutput(args: GetInstanceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetInstanceResult> {
    return pulumi.output(args).apply((a: any) => getInstance(a, opts))
}

/**
 * A collection of arguments for invoking getInstance.
 */
export interface GetInstanceOutputArgs {
    name: pulumi.Input<string>;
}
